# Uncomment the next line to define a global platform for your project

target 'CommunityAdmin' do
  # Comment the next line if you don't want to use dynamic frameworks
  platform :ios, '14.1'
  use_frameworks!

  # Pods for CommunityAdmin
  pod 'shared', :path => '../shared'

  target 'CommunityAdminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommunityAdminUITests' do
    # Pods for testing
  end

end
